name: Setup project via Conan
description: A workflow to setup (and optionally build) the project using Conan and CMake

inputs:
  profile:
    description: "Conan (build) profile to use. [Values: See `conan/profiles` folder]"
    type: string
    required: false
    default: "windows-msvc"
  arch:
    description: "The architecture to use for the setup. [Values: x86]"
    type: string
    required: true
    default: "x86"
    options:
      - x86
  conf:
    description: "The build configuration to use for the setup. [Values: Debug, Release]"
    required: true
    options:
      - Debug
      - Release
  unity_build:
    description: "Enable or disable Unity build. [Values: true, false]"
    type: boolean
    required: false
    default: false
  standalone:
    description: "Standalone (exe instead of dll) build mode [Values: false, dump_hooks_only]"
    type: string
    required: false
    default: "false"
    options:
      - "false"
      - "dump_hooks_only"
  build:
    description: "Whether to build the project after setting up CMake and Conan. [Values: true, false]"
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install Conan
      uses: conan-io/setup-conan@v1
      with:
        profile_detect: true

    - name: Setup Conan profiles
      shell: bash
      run: |
          # Name of the profile, this can be anything as long as it doesn't conflict with existing ones
          CI_PROFILE_NAME="ci_host_profile"

          # Generate a dynamic build profile for Conan based on the inputs provided to the action
          cat << EOF > ./conan/profiles/$CI_PROFILE_NAME
            include(${{ inputs.profile }}.txt)

            [settings]
            build_type=${{ inputs.conf }}
            arch=${{ inputs.arch }}

            [options]
            &:unity_build=${{ inputs.unity_build == 'true' && 'True' || 'False' }}
            &:standalone=${{ inputs.standalone == 'false' && 'False' || inputs.standalone }}
          EOF

          # Install it to the Conan cache
          conan config install ./conan/

          # Make Conan use the generated profile
          echo "CONAN_DEFAULT_PROFILE=$CI_PROFILE_NAME" >> $GITHUB_ENV

    - name: Setup project dependencies via Conan
      shell: bash
      run: >
        conan install . --build=missing

    - name: Setup dependencies and build project using Conan
      if: ${{ inputs.build == 'true' }}
      shell: bash
      run: >
        conan build .
