name: Setup project via Conan
description: A workflow to setup (and optionally build) the project using Conan and CMake

inputs:
  host_profile:
    description: "Conan (host) profile to use. [Values: See `conan/profiles` folder]"
    type: string
    required: false
    default: "windows-msvc"
  arch:
    description: "The architecture to use for the setup. [Values: x86]"
    type: string
    required: true
    default: "x86"
    options:
      - x86
  conf:
    description: "The build configuration to use for the setup. [Values: Debug, Release]"
    required: true
    options:
      - Debug
      - Release
  unity_build:
    description: "Enable or disable Unity build. [Values: true, false]"
    type: boolean
    required: false
    default: false
  standalone:
    description: "Standalone (exe instead of dll) build mode [Values: false, dump_hooks_only]"
    type: string
    required: false
    default: "false"
    options:
      - "false"
      - "dump_hooks_only"
  build:
    description: "Whether to build the project after setting up CMake and Conan. [Values: true, false]"
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install Conan
      uses: conan-io/setup-conan@v1
      with:
        profile_detect: true

    - name: Check CMake version
      shell: bash
      run: cmake --version


    - name: Setup project dependencies via Conan
      shell: bash
      run: >
        conan install . 
          ${{ inputs.build == 'true' && '--build=missing' || '' }}
          -o unity_build=${{ inputs.unity_build == 'true' && 'True' || 'False' }}
          -o standalone=${{ inputs.standalone == 'false' && 'False' || inputs.standalone }}
          -s build_type=${{ inputs.conf }}
          -s arch=${{ inputs.arch }}

    - name: Setup dependencies and build project using Conan
      if: ${{ inputs.build == 'true' }}
      shell: bash
      run: >
        conan build .
          -o unity_build=${{ inputs.unity_build == 'true' && 'True' || 'False' }}
          -o standalone=${{ inputs.standalone == 'false' && 'False' || inputs.standalone }}
          -s build_type=${{ inputs.conf }}
          -s arch=${{ inputs.arch }}
